AngularTraining/Controllers/CategoryMVCOnlyController.cs
namespace AngularStart.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Models;

    public class CategoryMVCOnlyController : Controller
    {
        private readonly DataContext context = new DataContext();
        //
        // GET: /CategoryMVCOnly/

        public ActionResult Index(int? id = 1)
        {
            try
            {
                var category = context.Categories.Find(id);
                var model = new CategoryViewModel
                {
                    Categories = context.Categories,
                    SelectedCategoryId = category.Id
                };
                return View(model);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        public ActionResult BrandsPartial(int? id = 1)
        {
            try
            {
                var category = context.Categories.Find(id);

                var modelToView = new BrandViewModel
                {
                    Brands = id != 1 ? context.Brands.Where(x => x.CategoryId == id) : context.Brands,
                    SelectedCategoryId = category.Id
                };
                return PartialView(modelToView);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        //
        // GET: /CategoryMVCOnly/Edit/5
        public ActionResult Edit(int id, int redirect)
        {
            try
            {
                var modelToView = new SingleBrandViewModel
                {
                    CurrBrand = context.Brands.Find(id),
                    SelectedCategoryId = redirect
                };
                return View(modelToView);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        //
        // POST: /CategoryMVCOnly/Edit/5

        [HttpPost]
        public ActionResult Edit(SingleBrandViewModel model, int redirect)
        {
            try
            {
                var brand = context.Brands.Find(model.CurrBrand.Id);
                brand.Title = model.CurrBrand.Title;

                context.SaveChanges();

                return RedirectToAction("Index", new { id = redirect });
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

AngularTraining/Views/CategoryMVCOnly/BrandsPartial.cshtml
@model AngularStart.Models.BrandViewModel

<div class="span9">
    <div class="row">
        @if (Model.Brands != null)
        {
            foreach (var brand in Model.Brands)
            {
                <div class=" col-md-2">
                    <a href="@Url.Action("Edit", "CategoryMVCOnly", new { id = brand.Id, redirect = Model.SelectedCategoryId })" class="thumbnail" id="brandItem">
                        <img src="@brand.ImageUrl" />
                        <div class="caption">
                            @brand.Title
                        </div>
                    </a>
                </div>
            }
        }
    </div>
</div>

AngularTraining/Views/CategoryMVCOnly/Edit.cshtml
@model AngularStart.Models.SingleBrandViewModel
@{
    ViewBag.Title = "Edit";
}
<h2>Edit MVC Only</h2>

@using (Html.BeginForm("Edit", "CategoryMVCOnly", new { redirect = Model.SelectedCategoryId }, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken();
    @Html.HiddenFor(model => model.CurrBrand.Id)
    <div class="control-group" ng-class="{error: form.Title.$invalid}">
        <label class="control-label" for="ImageUrl">Image</label>
        <div class="controls">
            <img src="@Model.CurrBrand.ImageUrl" width="150" height="150" id="ImageUrl" />
        </div>
        <br />
        <label class="control-label" for="Title">Title</label>
        <div class="controls">
            @Html.TextBoxFor(model => model.CurrBrand.Title)
        </div>

    </div>
    <div class="form-actions">
        <button class="btn btn-primary" name="btn" value="Update">
            Update
        </button>
        @*<back-button to="{{item.CategoryId}}" />*@

        <a href="@Url.Action("Index", "CategoryMVCOnly", new { id = Model.SelectedCategoryId })" class="btn btn-danger">Cancel</a>

    </div>
}

AngularTraining/Views/CategoryMVCOnly/Index.cshtml
@model AngularStart.Models.CategoryViewModel
@{
    ViewBag.Title = "CategoryMVCOnly";
}

<h2>Category MVC Only</h2>

<br />
<div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-list">
            @foreach (var category in Model.Categories)
            {
                if (Model.SelectedCategoryId == category.Id)
                {
                <li class="active" style="padding: 2px 2px 2px 2px">
                    <a href="@Url.Action("Index", "CategoryMVCOnly", new { id = category.Id })">
                        <div class="row-fluid">
                            <img src="@category.ImageUrl" width="50" height="50" style="padding-right: 7px" />
                            @category.Title
                        </div>
                    </a>
                </li>
                }
                else
                {
                <li style="padding: 2px 2px 2px 2px">
                    <a href="@Url.Action("Index", "CategoryMVCOnly", new { id = category.Id })">
                        <div class="row-fluid">
                            <img src="@category.ImageUrl" width="50" height="50" style="padding-right: 7px" />
                            @category.Title
                        </div>
                    </a>
                </li>
                }
            }
        </ul>
    </div>
    @{Html.RenderAction("BrandsPartial", "CategoryMVCOnly", new { id = Model.SelectedCategoryId });}

</div>